export type Language = 'en' | 'kn' | 'hi';

export const lexicon = {
    en: {
        // App-level
        app_name: "AarogyaVani",
        scanner: "Scanner",
        reminders: "Reminders",
        companion: "Companion",
        dashboard: "Dashboard",
        ai_reports: "AI Reports",
        calendar: "Calendar",
        sos: "SOS",
        settings: "Settings",
        docs_demo: "🚀 Docs & Demo",
        logout: "Logout",
        welcome: "Welcome,",
        patient_view: "Patient View",
        care_anchor_view: "Care Anchor Portal",
        scan_btn: "Scan Prescription",
        ask_ai: "Ask AI Assistant",
        streak: "Streak",
        days: "Days",
        what_is_this: "What is this medicine?",
        take_photo: "Take Photo",
        analyzing: "Analyzing with Gemini...",
        add_to_meds: "Add to My Medicines",
        emergency_call: "EMERGENCY CALL",
        notif_anchor: "Notify Care Anchor",
        lang_btn: "Change Language",
        back_to_login: "Back to Login",
        appointments: "Appointments",
        family: "Family",
        why_outstanding: "The Zero-Hardware, AI-First Companion for safe medication. Deciphers handwriting instantly.",
        // Auth page
        auth_sign_in: "Sign In",
        auth_create_account: "Create Account",
        auth_care_anchor: "Care Anchor",
        auth_your_name: "Your Name",
        auth_email: "Email Address",
        auth_password: "Password",
        auth_age: "Age",
        auth_optional: "Optional",
        auth_invite_anchor: "INVITE A CARE ANCHOR",
        auth_anchor_name: "Their Name",
        auth_anchor_phone: "Their Phone No.",
        auth_anchor_hint: "They will need this phone number to log in and monitor your health securely.",
        auth_sign_in_btn: "Sign In",
        auth_create_btn: "Create Account",
        auth_wait: "Please wait...",
        auth_link_patient: "🤝 Link Patient",
        auth_login_anchor: "🛡️ Log In as Anchor",
        auth_log_in: "Log In",
        auth_link_new: "Link New Patient",
        auth_phone: "Your Phone Number",
        auth_anchor_password: "Anchor Password",
        auth_create_password: "Create a password",
        auth_your_password: "Your password",
        auth_anchor_code: "Care Anchor Code",
        auth_anchor_code_desc: "To link a patient to your device, you must provide your name, register a persistent password, and enter the patient's unique 6-character code.",
        auth_privacy: "Your data stays strictly on your device. We do not share anything with remote cloud databases.",
        // Scanner tab
        sc_title: "Prescription Scanner",
        sc_subtitle: "Scan any handwritten prescription",
        sc_result_label: "Analysis Result",
        sc_upload_label: "Upload / Take a Photo",
        sc_add_confirm: "Add to My Medicines?",
        sc_add_name: "Medicine Name",
        sc_add_dosage: "Dosage",
        sc_add_times: "Times per Day",
        sc_confirm_btn: "Confirm & Add",
        sc_cancel_btn: "Cancel",
        sc_add_success: "Medicine added to your reminders!",
        sc_analyzing: "Analyzing your prescription with Gemini AI...",
        sc_error: "Could not decode prescription.",
        sc_tap_camera: "Tap to choose photo or use camera",
        sc_or_say: "or say",
        // Medication Reminders
        med_title: "Medication Reminders",
        med_subtitle: "Track your daily medicines",
        med_add: "+ Add Medicine",
        med_close: "✕ Close",
        med_name: "Medicine Name",
        med_dosage: "Dosage",
        med_schedule: "Schedule",
        med_notes: "Notes",
        med_language: "Language",
        med_save: "Save Medicine",
        med_mark_taken: "Mark Taken",
        med_skip: "Skip",
        med_taken: "Taken",
        med_skipped: "Skipped",
        med_due: "Due",
        med_no_meds: "No medicines added yet.",
        med_add_first: "Add your first medicine to get started.",
        med_today: "Today's Schedule",
        med_streak: "day streak!",
        med_praise_1: "Excellent work!",
        // Appointment Calendar
        appt_title: "Doctor Appointments",
        appt_subtitle: "Schedule and track your visits",
        appt_add: "+ Add Appointment",
        appt_close: "✕ Close",
        appt_form_title: "New Appointment",
        appt_label_title: "Appointment Title",
        appt_label_doctor: "Doctor Name",
        appt_label_date: "Date",
        appt_label_time: "Time",
        appt_label_location: "Hospital / Clinic Location",
        appt_save: "Save Appointment",
        appt_upcoming: "Upcoming Appointments",
        appt_none_day: "No appointments on this day",
        appt_add_one: "+ Add one",
        appt_no_upcoming: "No upcoming appointments",
        appt_managing: "Managing appointments for",
        // SOS
        sos_title: "SOS & Emergency",
        sos_call_help: "CALL FOR HELP",
        sos_alert_hint: "Alerts based on your settings below",
        sos_prefs_title: "What happens when SOS is pressed",
        sos_whatsapp: "Send WhatsApp Message",
        sos_whatsapp_sub: "Sends emergency text to your first contact",
        sos_anchor_alert: "Alert Care Anchor on App",
        sos_anchor_alert_sub: "Flags an emergency on your anchor's dashboard",
        sos_contacts: "Emergency Contacts",
        sos_add: "+ Add",
        sos_no_contacts: "No contacts added yet. Add a family member's number above.",
        sos_share_location: "Share My Location",
        sos_share_location_sub: "Sends GPS location via WhatsApp",
        sos_call_ambulance: "Call Ambulance",
        sos_checkin_sent: "Check-in sent!",
        sos_checkin_placeholder: "Type a check-in message...",
        sos_send_checkin: "Send Check-In to Patient",
        sos_alert_banner: "SOS ALERT!",
        sos_alert_sub: "pressed the emergency button at",
        sos_dismiss: "Dismiss",
        sos_anchor_contacts: "Patient Emergency Contacts",
        sos_anchor_no_contacts: "No emergency contacts saved by the patient yet.",
        // Caregiver Dashboard
        cg_title: "Caregiver Dashboard",
        cg_subtitle: "Patient health overview",
        cg_managing: "Monitoring",
        cg_adherence: "Adherence Today",
        cg_taken: "Taken",
        cg_skipped: "Skipped",
        cg_upcoming: "Upcoming Appointments",
        cg_no_appts: "No upcoming appointments",
        cg_contacts: "Emergency Contacts",
        cg_no_contacts: "No emergency contacts added",
        cg_copy_code: "Copy Anchor Code",
        cg_copied: "Copied!",
        // Settings
        set_title: "Settings",
        set_api_key: "Gemini API Key",
        set_api_save: "Save Key",
        set_api_saved: "Saved!",
        set_api_placeholder: "Paste your Gemini API key here",
        set_language: "Language",
        set_theme: "Theme",
        set_dark: "Dark",
        set_light: "Light",
        // Common
        save: "Save",
        cancel: "Cancel",
        delete: "Delete",
        close: "Close",
        loading: "Loading...",
        per_day: "per day",
    },
    kn: {
        // App-level
        app_name: "ಆರೋಗ್ಯವಾಣಿ",
        scanner: "ಸ್ಕ್ಯಾನರ್",
        reminders: "ಜ್ಞಾಪನೆಗಳು",
        companion: "ಸಂಗಾತಿ",
        dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        ai_reports: "AI ವರದಿಗಳು",
        calendar: "ಕ್ಯಾಲೆಂಡರ್",
        sos: "ತುರ್ತು ಸಹಾಯ",
        settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        docs_demo: "🚀 ಮಾಹಿತಿ ಮತ್ತು ಪ್ರದರ್ಶನ",
        logout: "ಲಾಗ್ ಔಟ್",
        welcome: "ಸ್ವಾಗತ,",
        patient_view: "ರೋಗಿಗಳ ವೀಕ್ಷಣೆ",
        care_anchor_view: "ಆರೈಕೆ ಆಂಕರ್ ಪೋರ್ಟಲ್",
        scan_btn: "ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
        ask_ai: "AI ಸಹಾಯಕನನ್ನು ಕೇಳಿ",
        streak: "ಸತತ ದಿನಗಳು",
        days: "ದಿನಗಳು",
        what_is_this: "ಈ ಔಷಧಿ ಯಾವುದು?",
        take_photo: "ಫೋಟೋ ತೆಗೆಯಿರಿ",
        analyzing: "ಜೆಮಿನಿ ಮೂಲಕ ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
        add_to_meds: "ನನ್ನ ಔಷಧಿಗಳಿಗೆ ಸೇರಿಸಿ",
        emergency_call: "ತುರ್ತು ಕರೆ",
        notif_anchor: "ಆರೈಕೆ ಆಂಕರ್‌ಗೆ ತಿಳಿಸಿ",
        lang_btn: "ಭಾಷೆ ಬದಲಾಯಿಸಿ",
        back_to_login: "ಲಾಗಿನ್‌ಗೆ ಹಿಂತಿರುಗಿ",
        appointments: "ನೇಮಕಾತಿಗಳು",
        family: "ಕುಟುಂಬ",
        why_outstanding: "ಹಾರ್ಡ್‌ವೇರ್ ಇಲ್ಲದ, AI ಆಧಾರಿತ ಸುರಕ್ಷಿತ ಔಷಧ ಸಂಗಾತಿ. ಕೈ ಬರಹವನ್ನು ಕ್ಷಣಾರ್ಧದಲ್ಲಿ ಓದುತ್ತದೆ.",
        // Auth page
        auth_sign_in: "ಸೈನ್ ಇನ್",
        auth_create_account: "ಖಾತೆ ರಚಿಸಿ",
        auth_care_anchor: "ಆರೈಕೆ ಆಂಕರ್",
        auth_your_name: "ನಿಮ್ಮ ಹೆಸರು",
        auth_email: "ಇಮೇಲ್ ವಿಳಾಸ",
        auth_password: "ಪಾಸ್‌ವರ್ಡ್",
        auth_age: "ವಯಸ್ಸು",
        auth_optional: "ಐಚ್ಛಿಕ",
        auth_invite_anchor: "ಆರೈಕೆ ಆಂಕರ್ ಆಹ್ವಾನಿಸಿ",
        auth_anchor_name: "ಅವರ ಹೆಸರು",
        auth_anchor_phone: "ಅವರ ದೂರವಾಣಿ ಸಂಖ್ಯೆ",
        auth_anchor_hint: "ದೂರವಾಣಿ ಸಂಖ್ಯೆ ಬಳಸಿ ಅವರು ನಿಮ್ಮ ಆರೋಗ್ಯ ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಬಹುದು.",
        auth_sign_in_btn: "ಸೈನ್ ಇನ್",
        auth_create_btn: "ಖಾತೆ ರಚಿಸಿ",
        auth_wait: "ದಯವಿಟ್ಟು ನಿರೀಕ್ಷಿಸಿ...",
        auth_link_patient: "🤝 ರೋಗಿ ಲಿಂಕ್ ಮಾಡಿ",
        auth_login_anchor: "🛡️ ಆಂಕರ್ ಲಾಗಿನ್",
        auth_log_in: "ಲಾಗ್ ಇನ್",
        auth_link_new: "ಹೊಸ ರೋಗಿ ಲಿಂಕ್ ಮಾಡಿ",
        auth_phone: "ನಿಮ್ಮ ದೂರವಾಣಿ ಸಂಖ್ಯೆ",
        auth_anchor_password: "ಆಂಕರ್ ಪಾಸ್‌ವರ್ಡ್",
        auth_create_password: "ಪಾಸ್‌ವರ್ಡ್ ರಚಿಸಿ",
        auth_your_password: "ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್",
        auth_anchor_code: "ಆರೈಕೆ ಆಂಕರ್ ಕೋಡ್",
        auth_anchor_code_desc: "ರೋಗಿಯನ್ನು ಲಿಂಕ್ ಮಾಡಲು ನಿಮ್ಮ ಹೆಸರು, ಪಾಸ್‌ವರ್ಡ್ ಮತ್ತು 6-ಅಕ್ಷರದ ಕೋಡ್ ನೀಡಿ.",
        auth_privacy: "ನಿಮ್ಮ ಡೇಟಾ ಸಂಪೂರ್ಣ ನಿಮ್ಮ ಸಾಧನದಲ್ಲೇ ಉಳಿಯುತ್ತದೆ.",
        // Scanner
        sc_title: "ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಸ್ಕ್ಯಾನರ್",
        sc_subtitle: "ಯಾವುದೇ ಕೈ ಬರಹದ ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
        sc_result_label: "ವಿಶ್ಲೇಷಣೆ ಫಲಿತಾಂಶ",
        sc_upload_label: "ಫೋಟೋ ಅಪ್ಲೋಡ್ / ತೆಗೆಯಿರಿ",
        sc_add_confirm: "ನನ್ನ ಔಷಧಿಗಳಿಗೆ ಸೇರಿಸುವಿರಾ?",
        sc_add_name: "ಔಷಧಿ ಹೆಸರು",
        sc_add_dosage: "ಪ್ರಮಾಣ",
        sc_add_times: "ದಿನಕ್ಕೆ ಬಾರಿ",
        sc_confirm_btn: "ದೃಢಪಡಿಸಿ ಮತ್ತು ಸೇರಿಸಿ",
        sc_cancel_btn: "ರದ್ದು ಮಾಡಿ",
        sc_add_success: "ಔಷಧಿ ಜ್ಞಾಪನೆಗಳಿಗೆ ಸೇರಿಸಲಾಗಿದೆ!",
        sc_analyzing: "Gemini AI ಮೂಲಕ ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
        sc_error: "ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಓದಲಾಗಲಿಲ್ಲ.",
        sc_tap_camera: "ಫೋಟೋ ಆಯ್ಕೆ ಮಾಡಲು ಅಥವಾ ಕ್ಯಾಮೆರಾ ಬಳಸಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
        sc_or_say: "ಅಥವಾ ಹೇಳಿ",
        // Medication Reminders
        med_title: "ಔಷಧಿ ಜ್ಞಾಪನೆಗಳು",
        med_subtitle: "ನಿಮ್ಮ ದೈನಂದಿನ ಔಷಧಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
        med_add: "+ ಔಷಧಿ ಸೇರಿಸಿ",
        med_close: "✕ ಮುಚ್ಚಿ",
        med_name: "ಔಷಧಿ ಹೆಸರು",
        med_dosage: "ಪ್ರಮಾಣ",
        med_schedule: "ವೇಳಾಪಟ್ಟಿ",
        med_notes: "ಟಿಪ್ಪಣಿ",
        med_language: "ಭಾಷೆ",
        med_save: "ಔಷಧಿ ಉಳಿಸಿ",
        med_mark_taken: "ತೆಗೆದುಕೊಂಡಿದ್ದೇನೆ",
        med_skip: "ಬಿಟ್ಟುಬಿಡಿ",
        med_taken: "ತೆಗೆದುಕೊಂಡಿದ್ದಾರೆ",
        med_skipped: "ಬಿಟ್ಟಿದ್ದಾರೆ",
        med_due: "ಬಾಕಿ ಇದೆ",
        med_no_meds: "ಇನ್ನೂ ಯಾವುದೇ ಔಷಧಿ ಸೇರಿಸಿಲ್ಲ.",
        med_add_first: "ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಮೊದಲ ಔಷಧಿ ಸೇರಿಸಿ.",
        med_today: "ಇಂದಿನ ವೇಳಾಪಟ್ಟಿ",
        med_streak: "ದಿನ ಸತತ!",
        med_praise_1: "ಅದ್ಭುತ ಕೆಲಸ!",
        // Appointment Calendar
        appt_title: "ವೈದ್ಯರ ನೇಮಕಾತಿ",
        appt_subtitle: "ನಿಮ್ಮ ಭೇಟಿಗಳನ್ನು ಯೋಜಿಸಿ ಮತ್ತು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
        appt_add: "+ ನೇಮಕಾತಿ ಸೇರಿಸಿ",
        appt_close: "✕ ಮುಚ್ಚಿ",
        appt_form_title: "ಹೊಸ ನೇಮಕಾತಿ",
        appt_label_title: "ನೇಮಕಾತಿ ಶೀರ್ಷಿಕೆ",
        appt_label_doctor: "ವೈದ್ಯರ ಹೆಸರು",
        appt_label_date: "ದಿನಾಂಕ",
        appt_label_time: "ಸಮಯ",
        appt_label_location: "ಆಸ್ಪತ್ರೆ / ಕ್ಲಿನಿಕ್ ಸ್ಥಳ",
        appt_save: "ನೇಮಕಾತಿ ಉಳಿಸಿ",
        appt_upcoming: "ಮುಂಬರುವ ನೇಮಕಾತಿಗಳು",
        appt_none_day: "ಈ ದಿನ ಯಾವುದೇ ನೇಮಕಾತಿ ಇಲ್ಲ",
        appt_add_one: "+ ಸೇರಿಸಿ",
        appt_no_upcoming: "ಮುಂಬರುವ ನೇಮಕಾತಿಗಳಿಲ್ಲ",
        appt_managing: "ನೇಮಕಾತಿ ನಿರ್ವಹಿಸಲಾಗುತ್ತಿದೆ",
        // SOS
        sos_title: "ತುರ್ತು ಸಹಾಯ",
        sos_call_help: "ಸಹಾಯಕ್ಕೆ ಕರೆ ಮಾಡಿ",
        sos_alert_hint: "ನಿಮ್ಮ ಸೆಟ್ಟಿಂಗ್ ಆಧಾರದ ಮೇಲೆ ಎಚ್ಚರಿಕೆ",
        sos_prefs_title: "SOS ಒತ್ತಿದಾಗ ಏನಾಗುತ್ತದೆ",
        sos_whatsapp: "WhatsApp ಸಂದೇಶ ಕಳಿಸಿ",
        sos_whatsapp_sub: "ಮೊದಲ ಸಂಪರ್ಕಕ್ಕೆ ತುರ್ತು ಸಂದೇಶ ಕಳಿಸಿ",
        sos_anchor_alert: "ಆಪ್‌ನಲ್ಲಿ ಆರೈಕೆ ಆಂಕರ್‌ಗೆ ಎಚ್ಚರಿಕೆ",
        sos_anchor_alert_sub: "ನಿಮ್ಮ ಆಂಕರ್‌ನ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ನಲ್ಲಿ ತುರ್ತು ಸಂಕೇತ",
        sos_contacts: "ತುರ್ತು ಸಂಪರ್ಕಗಳು",
        sos_add: "+ ಸೇರಿಸಿ",
        sos_no_contacts: "ಇನ್ನೂ ಯಾವುದೇ ಸಂಪರ್ಕ ಸೇರಿಸಿಲ್ಲ.",
        sos_share_location: "ನನ್ನ ಸ್ಥಳ ಹಂಚಿಕೊಳ್ಳಿ",
        sos_share_location_sub: "WhatsApp ಮೂಲಕ GPS ಸ್ಥಳ ಕಳಿಸಿ",
        sos_call_ambulance: "ಆಂಬ್ಯುಲೆನ್ಸ್ ಕರೆ ಮಾಡಿ",
        sos_checkin_sent: "ಚೆಕ್-ಇನ್ ಕಳಿಸಲಾಗಿದೆ!",
        sos_checkin_placeholder: "ಚೆಕ್-ಇನ್ ಸಂದೇಶ ಟೈಪ್ ಮಾಡಿ...",
        sos_send_checkin: "ರೋಗಿಗೆ ಚೆಕ್-ಇನ್ ಕಳಿಸಿ",
        sos_alert_banner: "ತುರ್ತು ಸಂಕೇತ!",
        sos_alert_sub: "ತುರ್ತು ಬಟನ್ ಒತ್ತಿದ್ದಾರೆ",
        sos_dismiss: "ವಜಾ ಮಾಡಿ",
        sos_anchor_contacts: "ರೋಗಿಯ ತುರ್ತು ಸಂಪರ್ಕಗಳು",
        sos_anchor_no_contacts: "ರೋಗಿ ಇನ್ನೂ ಯಾವುದೇ ತುರ್ತು ಸಂಪರ್ಕ ಉಳಿಸಿಲ್ಲ.",
        // Caregiver Dashboard
        cg_title: "ಆರೈಕೆದಾರರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        cg_subtitle: "ರೋಗಿಯ ಆರೋಗ್ಯ ಸಾರಾಂಶ",
        cg_managing: "ಮೇಲ್ವಿಚಾರಣೆ",
        cg_adherence: "ಇಂದಿನ ಅನುಸರಣೆ",
        cg_taken: "ತೆಗೆದುಕೊಂಡಿದ್ದಾರೆ",
        cg_skipped: "ಬಿಟ್ಟಿದ್ದಾರೆ",
        cg_upcoming: "ಮುಂಬರುವ ನೇಮಕಾತಿಗಳು",
        cg_no_appts: "ಮುಂಬರುವ ನೇಮಕಾತಿಗಳಿಲ್ಲ",
        cg_contacts: "ತುರ್ತು ಸಂಪರ್ಕಗಳು",
        cg_no_contacts: "ತುರ್ತು ಸಂಪರ್ಕಗಳಿಲ್ಲ",
        cg_copy_code: "ಆಂಕರ್ ಕೋಡ್ ನಕಲಿಸಿ",
        cg_copied: "ನಕಲಿಸಲಾಗಿದೆ!",
        // Settings
        set_title: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        set_api_key: "Gemini API ಕೀ",
        set_api_save: "ಕೀ ಉಳಿಸಿ",
        set_api_saved: "ಉಳಿಸಲಾಗಿದೆ!",
        set_api_placeholder: "ನಿಮ್ಮ Gemini API ಕೀ ಇಲ್ಲಿ ಅಂಟಿಸಿ",
        set_language: "ಭಾಷೆ",
        set_theme: "ಥೀಮ್",
        set_dark: "ಕತ್ತಲು",
        set_light: "ಬೆಳಕು",
        // Common
        save: "ಉಳಿಸಿ",
        cancel: "ರದ್ದು",
        delete: "ಅಳಿಸಿ",
        close: "ಮುಚ್ಚಿ",
        loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
        per_day: "ದಿನಕ್ಕೆ",
    },
    hi: {
        // App-level
        app_name: "आरोग्यवाणी",
        scanner: "स्कैनर",
        reminders: "अनुस्मारक",
        companion: "साथी",
        dashboard: "डैशबोर्ड",
        ai_reports: "AI रिपोर्ट",
        calendar: "कैलेंडर",
        sos: "आपातकाल",
        settings: "सेटिंग्स",
        docs_demo: "🚀 जानकारी और डेमो",
        logout: "लॉगआउट",
        welcome: "स्वागत है,",
        patient_view: "मरीज दृश्य",
        care_anchor_view: "केयर एंकर पोर्टल",
        scan_btn: "पर्चे को स्कैन करें",
        ask_ai: "AI सहायक से पूछें",
        streak: "लगातार दिन",
        days: "दिन",
        what_is_this: "यह दवा क्या है?",
        take_photo: "फोटो लें",
        analyzing: "जेमिनी विश्लेषण कर रहा है...",
        add_to_meds: "मेरी दवाओं में जोड़ें",
        emergency_call: "आपातकालीन कॉल",
        notif_anchor: "केयर एंकर को सूचित करें",
        lang_btn: "भाषा बदलें",
        back_to_login: "लॉगिन पर वापस जाएं",
        appointments: "अपॉइंटमेंट",
        family: "परिवार",
        why_outstanding: "बिना हार्डवेयर के, सुरक्षित दवा के लिए AI साथी। हस्तलेखन को तुरंत पढ़ता है।",
        // Auth page
        auth_sign_in: "साइन इन",
        auth_create_account: "खाता बनाएं",
        auth_care_anchor: "केयर एंकर",
        auth_your_name: "आपका नाम",
        auth_email: "ईमेल पता",
        auth_password: "पासवर्ड",
        auth_age: "आयु",
        auth_optional: "वैकल्पिक",
        auth_invite_anchor: "केयर एंकर को आमंत्रित करें",
        auth_anchor_name: "उनका नाम",
        auth_anchor_phone: "उनका फोन नंबर",
        auth_anchor_hint: "वे इस फोन नंबर से लॉगिन कर आपके स्वास्थ्य की देखरेख कर सकते हैं।",
        auth_sign_in_btn: "साइन इन",
        auth_create_btn: "खाता बनाएं",
        auth_wait: "कृपया प्रतीक्षा करें...",
        auth_link_patient: "🤝 मरीज को लिंक करें",
        auth_login_anchor: "🛡️ एंकर लॉगिन",
        auth_log_in: "लॉग इन",
        auth_link_new: "नया मरीज लिंक करें",
        auth_phone: "आपका फोन नंबर",
        auth_anchor_password: "एंकर पासवर्ड",
        auth_create_password: "पासवर्ड बनाएं",
        auth_your_password: "आपका पासवर्ड",
        auth_anchor_code: "केयर एंकर कोड",
        auth_anchor_code_desc: "मरीज को लिंक करने के लिए अपना नाम, पासवर्ड और 6-अक्षर का कोड दर्ज करें।",
        auth_privacy: "आपका डेटा पूरी तरह आपके डिवाइस पर रहता है।",
        // Scanner
        sc_title: "पर्चा स्कैनर",
        sc_subtitle: "कोई भी हस्तलिखित पर्चा स्कैन करें",
        sc_result_label: "विश्लेषण परिणाम",
        sc_upload_label: "फोटो अपलोड / लें",
        sc_add_confirm: "मेरी दवाओं में जोड़ें?",
        sc_add_name: "दवा का नाम",
        sc_add_dosage: "खुराक",
        sc_add_times: "प्रतिदिन बार",
        sc_confirm_btn: "पुष्टि करें और जोड़ें",
        sc_cancel_btn: "रद्द करें",
        sc_add_success: "दवा अनुस्मारकों में जोड़ी गई!",
        sc_analyzing: "Gemini AI से विश्लेषण हो रहा है...",
        sc_error: "पर्चा नहीं पढ़ा जा सका।",
        sc_tap_camera: "फोटो चुनने या कैमरा उपयोग करने के लिए टैप करें",
        sc_or_say: "या कहें",
        // Medication Reminders
        med_title: "दवा अनुस्मारक",
        med_subtitle: "अपनी दैनिक दवाएं ट्रैक करें",
        med_add: "+ दवा जोड़ें",
        med_close: "✕ बंद",
        med_name: "दवा का नाम",
        med_dosage: "खुराक",
        med_schedule: "समय-सारणी",
        med_notes: "नोट्स",
        med_language: "भाषा",
        med_save: "दवा सहेजें",
        med_mark_taken: "ली गई",
        med_skip: "छोड़ें",
        med_taken: "ली गई",
        med_skipped: "छोड़ी गई",
        med_due: "बाकी है",
        med_no_meds: "अभी तक कोई दवा नहीं जोड़ी गई।",
        med_add_first: "शुरू करने के लिए अपनी पहली दवा जोड़ें।",
        med_today: "आज की समय-सारणी",
        med_streak: "दिन की स्ट्रीक!",
        med_praise_1: "शानदार काम!",
        // Appointment Calendar
        appt_title: "डॉक्टर अपॉइंटमेंट",
        appt_subtitle: "अपनी मुलाकातें शेड्यूल करें और ट्रैक करें",
        appt_add: "+ अपॉइंटमेंट जोड़ें",
        appt_close: "✕ बंद",
        appt_form_title: "नया अपॉइंटमेंट",
        appt_label_title: "अपॉइंटमेंट शीर्षक",
        appt_label_doctor: "डॉक्टर का नाम",
        appt_label_date: "तारीख",
        appt_label_time: "समय",
        appt_label_location: "अस्पताल / क्लिनिक स्थान",
        appt_save: "अपॉइंटमेंट सहेजें",
        appt_upcoming: "आगामी अपॉइंटमेंट",
        appt_none_day: "इस दिन कोई अपॉइंटमेंट नहीं",
        appt_add_one: "+ जोड़ें",
        appt_no_upcoming: "कोई आगामी अपॉइंटमेंट नहीं",
        appt_managing: "के लिए अपॉइंटमेंट प्रबंधित",
        // SOS
        sos_title: "आपातकालीन सहायता",
        sos_call_help: "मदद के लिए कॉल करें",
        sos_alert_hint: "आपकी सेटिंग के आधार पर अलर्ट",
        sos_prefs_title: "SOS दबाने पर क्या होगा",
        sos_whatsapp: "WhatsApp संदेश भेजें",
        sos_whatsapp_sub: "पहले संपर्क को आपातकालीन संदेश भेजें",
        sos_anchor_alert: "ऐप पर केयर एंकर को सूचित करें",
        sos_anchor_alert_sub: "आपके एंकर के डैशबोर्ड पर आपातकाल दिखाएं",
        sos_contacts: "आपातकालीन संपर्क",
        sos_add: "+ जोड़ें",
        sos_no_contacts: "अभी तक कोई संपर्क नहीं जोड़ा गया।",
        sos_share_location: "मेरा स्थान साझा करें",
        sos_share_location_sub: "WhatsApp से GPS स्थान भेजें",
        sos_call_ambulance: "एम्बुलेंस बुलाएं",
        sos_checkin_sent: "चेक-इन भेजा गया!",
        sos_checkin_placeholder: "चेक-इन संदेश टाइप करें...",
        sos_send_checkin: "मरीज को चेक-इन भेजें",
        sos_alert_banner: "आपातकालीन अलर्ट!",
        sos_alert_sub: "ने आपातकालीन बटन दबाया",
        sos_dismiss: "बंद करें",
        sos_anchor_contacts: "मरीज के आपातकालीन संपर्क",
        sos_anchor_no_contacts: "मरीज ने अभी तक कोई आपातकालीन संपर्क नहीं सहेजा।",
        // Caregiver Dashboard
        cg_title: "देखभालकर्ता डैशबोर्ड",
        cg_subtitle: "मरीज के स्वास्थ्य का सारांश",
        cg_managing: "निगरानी",
        cg_adherence: "आज की पालना",
        cg_taken: "ली गई",
        cg_skipped: "छोड़ी गई",
        cg_upcoming: "आगामी अपॉइंटमेंट",
        cg_no_appts: "कोई आगामी अपॉइंटमेंट नहीं",
        cg_contacts: "आपातकालीन संपर्क",
        cg_no_contacts: "कोई आपातकालीन संपर्क नहीं",
        cg_copy_code: "एंकर कोड कॉपी करें",
        cg_copied: "कॉपी किया!",
        // Settings
        set_title: "सेटिंग्स",
        set_api_key: "Gemini API कुंजी",
        set_api_save: "कुंजी सहेजें",
        set_api_saved: "सहेजा गया!",
        set_api_placeholder: "अपनी Gemini API कुंजी यहां पेस्ट करें",
        set_language: "भाषा",
        set_theme: "थीम",
        set_dark: "अंधेरा",
        set_light: "उजाला",
        // Common
        save: "सहेजें",
        cancel: "रद्द करें",
        delete: "हटाएं",
        close: "बंद करें",
        loading: "लोड हो रहा है...",
        per_day: "प्रतिदिन",
    }
};
